# apiVersion: v1
# kind: Secret
# metadata:
#   name: hello-world-secret-test
#   labels:
#     app: hello-world-test
#   namespace: test

# type: Opaque
# stringData:
#   NAME: aGVyYW1iCg==

apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret-test
  labels:
    app: hello-world-test
  annotations:
    avp.kubernetes.io/path: demo/secret
type: Opaque
stringData:
  password: <name>
