apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-test-1
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/my-apps/app1
    repoURL: https://github.com/heramb03/argo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
